engines:
  checkstyle:
    enabled: true
    channel: "beta"
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript

ratings:
  paths:
  - "**/*.java"
  - "**/*.js"
  - "**/*.css"

exclude_paths:
  - documents
  - src/design
  - src/jenkins

